# Site settings
title:  Matt Del
email: matt@mattdel.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
twitter_username: thegreydel
github_username:  mattdel19
baseurl: "/matt-del"

# Build settings
markdown: kramdown
permalink: pretty
